import type { Metadata } from "next";
import { Geist, Geist_Mono ,EB_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import Nav from "./_components/Nav";
import Providers from "./providers/providers";
import { Toaster } from "@/components/ui/toaster";
import { Roboto } from 'next/font/google'
import WhatsApp from "./_components/WhatsApp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})
 
const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], 
});


export const metadata: Metadata = {
  title: "AYUR MANTHRA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${roboto.className}  ${ebGaramond.variable}  ${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <Providers>
          <Navbar />
          <Nav />
          {children}
          <WhatsApp/>
          <Footer />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
